from single_mother import *

def main():
    print("You are entering the Single Mother Financial Simulator. Press enter to continue.")
    input()
    name = input("Enter your chosen name: ")
    print()
    values0 = overview(name)
    values1 = day_one(values0, name)
    values2 = day_two(values1, name)
    values3 = day_three(values2, name)
    values4 = day_four(values3, name)
    values5 = day_five(values4, name)
    values6 = day_six(values5, name)
    values7 = day_seven(values6)
    values8 = day_nine(values7)
    values9 = day_twelve(values8, name)
    values10 = day_thirteen(values9, name)
    values11 = day_fifteen(values10)
    values12 = day_seventeen(values11, name)
    values13 = day_eighteen(values12, name)
    values14 = day_twenty(values13, name)
    values15 = day_twenty_one(values14, name)
    values16 = day_twenty_two(values15, name)
    values17 = day_twenty_four(values16, name)
    values18 = day_twenty_seven(values17, name)
    values19 = day_twenty_eight(values18)
    values20 = day_twenty_nine(values19)
    values21 = day_thirty(values20, name)
    print("Thank you for playing.")
    print("Designed by Natalie Frank.")
if __name__ == '__main__':
	main()
